### PR TITLE
End of sprint checking

### PR DESCRIPTION
**Pull request by serge-gaia**
This change is [Reviewable](https://reviewable.io/reviews/parksandwildlife/ledger/196)

### CODE REVIEW

**Comment by scottp-dpaw** [comment]
:lgtm:

---

Reviewed 17 of 30 files at r6, 4 of 4 files at r7, 11 of 11 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/parksandwildlife/ledger/196#-:-KeasW5NevG7VGq5NFvb:bnfp4nl)*

**Comment by scottp-dpaw** [comment]
@serge-gaia could you rebase against the current master? thanks!

**Comment by serge-gaia** [comment]
@scottp-dpaw . Did merge the changes made by Brian about payment error (we changed a bit the way he did it). Also added two minor fixes.

**Comment by scottp-dpaw** [comment]
Reviewed 4 of 4 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/parksandwildlife/ledger/196)*

**Pull request merged**
